name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.3-alpine3.11
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Building static webpage
        run: npm run build
      - name: Load environment variables
        run: source .env
      - name: Push to GitHub Pages repository
        uses: cpina/github-action-push-to-another-repository@v1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: '${{ github.repository_owner }}.github.io'
          user-email: $REACT_APP_EMAIL
